Traceback (most recent call last):
  File "subscriber.py", line 118, in <module>
    main ()
  File "subscriber.py", line 100, in main
    sub1 = Subscriber(args.topic,args.id,args.ip)
  File "subscriber.py", line 21, in __init__
    self.config = json.load(fin)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
