Instantiating the broker or discovery server
Configurator changed use_broker from True to True
This is proxy: creating xsub and xpubsockets
Traceback (most recent call last):
  File "discovery_server_OR_broker.py", line 50, in <module>
    main ()
  File "discovery_server_OR_broker.py", line 46, in main
    bords = BorDS(args)
  File "discovery_server_OR_broker.py", line 31, in __init__
    xsubsocket.bind("tcp://*:5555")
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
Instantiating the broker or discovery server
Configurator changed use_broker from True to True
This is proxy: creating xsub and xpubsockets
Traceback (most recent call last):
  File "discovery_server_OR_broker.py", line 50, in <module>
    main ()
  File "discovery_server_OR_broker.py", line 46, in main
    bords = BorDS(args)
  File "discovery_server_OR_broker.py", line 31, in __init__
    xsubsocket.bind("tcp://*:5555")
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
