Connection dropped: socket connection error: Network is unreachable
Connection dropped: socket connection error: Network is unreachable
Connection dropped: socket connection error: Network is unreachable
Connection dropped: socket connection error: Network is unreachable
Connection dropped: socket connection error: Network is unreachable
Connection dropped: socket connection error: Network is unreachable
Connection dropped: socket connection error: Network is unreachable
Failed connecting to Zookeeper within the connection retry policy.
Instantiating the broker or discovery server
connecting to ZK: 10.0.2.15:2181
Traceback (most recent call last):
  File "dsorb.py", line 65, in <module>
    main ()
  File "dsorb.py", line 61, in main
    bords = BorDS(args)
  File "dsorb.py", line 31, in __init__
    zk = ZK(args, self.config, self.IP)
  File "/media/sf_VirtualBoxShare/CS6381_DistributedSystems/Assignment1/zk.py", line 25, in __init__
    self.zk.start()
  File "/home/rob/.local/lib/python3.6/site-packages/kazoo/client.py", line 635, in start
    raise self.handler.timeout_exception("Connection time-out")
kazoo.handlers.threading.KazooTimeoutError: Connection time-out
